source 'https://supermarket.getchef.com'
cookbook 'python', git: 'git://github.com/poise/python.git'
cookbook 'nginx', git: 'https://github.com/opscode-cookbooks/nginx'
cookbook 'postfix', git: 'https://github.com/opscode-cookbooks/postfix'
cookbook 'nginx-django', git: 'git://github.com/btnz/nginx-django.git'
cookbook 'gunicorn', git: 'git://github.com/opscode-cookbooks/gunicorn.git'
